version: '1'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  django:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8081:8081"
    networks:
      - mynetwork
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8081
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql

  react:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: npm start

networks:
  mynetwork:
    external: true