# Use an official Node runtime as the base image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json /app/

# Install app dependencies
RUN npm install

# Copy app source code
COPY . /app/

# Build the app
RUN npm run build