# Generated by Django 3.2.15 on 2023-06-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_answer_historicalanswer_historicalquestion_lowqualitypostscheck_notification_privrepnotification_rev'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalanswer',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical answer'},
        ),
        migrations.AlterModelOptions(
            name='historicalquestion',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical question'},
        ),
    ]
