# Generated by Django 3.2.6 on 2021-11-27 15:05

from django.db import migrations

from django.db import migrations
from django.utils import timezone

def saveTag(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    Tag.objects.get_or_create(name="Altruist", slug="altruist")
    Tag.objects.get_or_create(name="Benefactor", slug="benefactor")
    Tag.objects.get_or_create(name="Favorite Question", slug="favorite-question")
    Tag.objects.get_or_create(name="Stellar Question", slug="stellar-question")
    Tag.objects.get_or_create(name="Investor", slug="investor")
    Tag.objects.get_or_create(name="Nice Question", slug="nice-question")
    Tag.objects.get_or_create(name="Good Question", slug="good-question")
    Tag.objects.get_or_create(name="Great Question", slug="great-question")
    Tag.objects.get_or_create(name="Popular Question", slug="popular-question")
    Tag.objects.get_or_create(name="Notable Question", slug="notable-question")
    Tag.objects.get_or_create(name="Famous Question", slug="famous-question")
    Tag.objects.get_or_create(name="Promoter", slug="promoter")
    Tag.objects.get_or_create(name="Scholar", slug="scholar")
    Tag.objects.get_or_create(name="Student", slug="student")
    Tag.objects.get_or_create(name="Enlightened", slug="enlightened")
    Tag.objects.get_or_create(name="Explainer", slug="explainer")
    Tag.objects.get_or_create(name="Refiner", slug="refiner")
    Tag.objects.get_or_create(name="Illuminator", slug="illuminator")
    Tag.objects.get_or_create(name="Guru", slug="guru")
    Tag.objects.get_or_create(name="Lifejacket", slug="lifejacket")
    Tag.objects.get_or_create(name="Lifeboat", slug="lifeboat")
    Tag.objects.get_or_create(name="Nice Answer", slug="nice-answer")
    Tag.objects.get_or_create(name="Good Answer", slug="good-answer")
    Tag.objects.get_or_create(name="Great Answer", slug="great-answer")
    # Tag.objects.get_or_create(name="Populist", slug="populist")
    Tag.objects.get_or_create(name="Revival", slug="revival")
    Tag.objects.get_or_create(name="Necromancer", slug="necromancer")
    Tag.objects.get_or_create(name="Self-Learner", slug="self-learner")
    Tag.objects.get_or_create(name="Teacher", slug="teacher")
    # Tag.objects.get_or_create(name="Tanacious", slug="tanacious")
    # Tag.objects.get_or_create(name="Unsung Hero", slug="unsung-hero")
    Tag.objects.get_or_create(name="Autobiographer", slug="autobiographer")
    Tag.objects.get_or_create(name="Commentator", slug="commentator")
    Tag.objects.get_or_create(name="Pundit", slug="pundit")
    Tag.objects.get_or_create(name="Mortarboard", slug="mortarboard")
    Tag.objects.get_or_create(name="Epic", slug="epic")
    Tag.objects.get_or_create(name="Legendary", slug="legendary")
    # Tag.objects.get_or_create(name="Bronze Badge", slug="bronze-badge")
    # Tag.objects.get_or_create(name="Silver Badge", slug="silver-badge")
    # Tag.objects.get_or_create(name="Gold Badge", slug="gold-badge")
    Tag.objects.get_or_create(name="Citizen Patrol", slug="citizen-patrol")
    Tag.objects.get_or_create(name="Deputy", slug="deputy")
    Tag.objects.get_or_create(name="Marshal", slug="marshal")
    Tag.objects.get_or_create(name="Civic Duty", slug="civic-duty")
    Tag.objects.get_or_create(name="Critic", slug="critic")
    Tag.objects.get_or_create(name="Custodian", slug="custodian")
    Tag.objects.get_or_create(name="Reviewer", slug="reviewer")
    Tag.objects.get_or_create(name="Steward", slug="steward")
    Tag.objects.get_or_create(name="Disciplined", slug="disciplined")
    Tag.objects.get_or_create(name="Edit", slug="edit")
    Tag.objects.get_or_create(name="Strunk & White", slug="strunk-&-white")
    Tag.objects.get_or_create(name="Copy Editor", slug="copy-editor")
    Tag.objects.get_or_create(name="Electorate", slug="electorate")
    Tag.objects.get_or_create(name="Excavator", slug="excavator")
    Tag.objects.get_or_create(name="Archaologist", slug="archaologist")
    Tag.objects.get_or_create(name="Peer Pressure", slug="peer-pressure")
    Tag.objects.get_or_create(name="Proodreader", slug="proodreader")
    # Tag.objects.get_or_create(name="Sportsmanship", slug="sportsmanship")
    Tag.objects.get_or_create(name="Suffrage", slug="suffrage")
    Tag.objects.get_or_create(name="Supporter", slug="supporter")
    Tag.objects.get_or_create(name="Reversal", slug="reversal")
    # Tag.objects.get_or_create(name="Tubbleweed", slug="tubbleweed")
    Tag.objects.get_or_create(name="Vox Populi", slug="vox-populi")
    Tag.objects.get_or_create(name="Informed", slug="informed")


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.RunPython(saveTag),
    ]