# Generated by Django 3.2.15 on 2024-04-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_initial_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalanswer',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical answer', 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='historicalquestion',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical question', 'managed': False},
        ),
    ]
